### ISSUE TITLE
A11y_OSPO Production_Azure credits for open source projects_AI4W: Ensures elements with an ARIA role that require child roles contain them (.tabs__tabs)

### ISSUE THREAD

**Issue by NiharikaTipirishetty** [microsoft/opensource.microsoft.com#217] opened 2022-07-29 09:13 UTC
### Github tags:
#A11yMAS; #A11ySev2; #A11yTCS; #Benchmark; #P2_OSPOProduction_Web_Sep2021; #P2_WCP; #WCP; #OSPO Production; #DesktopWeb; #ChromiumEgde; #Win11; #P2_OSPOProduction; #WCAG1.3.1; #aria-required-children;

### Environment and OS Details:
#URL: https://opensource.microsoft.com/azure-credits
App name: OSPO Production
Windows 11 Version 21H2(OS Build 22000.795)
Chromium Edge Version 103.0.1264.62 (Official build) (64-bit)

### Note:
This issue is also observed in https://opensource.microsoft.com/program/

### Issue: 
Ensures elements with an ARIA role that require child roles contain them (aria-required-children - https://accessibilityinsights.io/info-examples/web/aria-required-children)

### Target application: 
Azure Credits for Open Source Projects | Microsoft Open Source - https://opensource.microsoft.com/azure-credits

### Element path: 
.tabs__tabs

### Snippet: 
ul class="tabs__tabs" role="tablist"

### How to fix: 
Fix any of the following:
  Required ARIA child role not present: tab

Environment: Microsoft Edge version 103.0.1264.71

====

This accessibility issue was found using Accessibility Insights for Web 2.32.0 (axe-core 4.4.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

### Attachments:
![Azure credits for open source projects_AI4W](https://user-images.githubusercontent.com/83570638/181726176-d6807f17-e70a-476d-bd39-a6e3fae97df9.png)
![Microsoft’s Open Source Program_AI4W](https://user-images.githubusercontent.com/83570638/181726292-392972e8-de3b-4328-80be-b37271059d78.png)

**Comment by mpcen** [comment] 2022-10-28 16:16
fixed in https://github.com/microsoft/opensource.microsoft.com/pull/236

this can be closed

**Closed** 2022-10-28 16:16 UTC
Labels: keep-me

**Comment by akashelijah05** [comment] 2022-10-31 10:59
Verified the issue in https://opensource.microsoft.com/azure-credits and the issue is fixed. Please find attached screen shot for reference. Thanks
![217_Fixed](https://user-images.githubusercontent.com/116360471/198992357-7836424f-9e5b-4806-a8e5-a70802b856b9.jpg)

Verified the similar issue in https://opensource.microsoft.com/program/ and the issue is fixed. Please find attached screen shot for reference. Thanks
![217_Similar issue fixed](https://user-images.githubusercontent.com/116360471/198992978-7a479957-fef7-4f68-b0e4-fc6e31402efc.jpg)
