### ISSUE TITLE
A11y_OSPO Production_Footer Section_Use of Color: The "Open Source" link present in the footer section is not provided with a underline.

### ISSUE THREAD

**Issue by Rachita98** [microsoft/opensource.microsoft.com#120] opened 2021-09-10 12:42 UTC
<h2>GitHub Tags:</h2>
#A11yTCS;#A11yMAS;#Win10;#DesktopWeb;#A11ySev2;#P2_WCP;#WCP;#P2_OSPOProduction_Web_Sep2021;#P2_OSPOProduction;#OSPO Production;#WCAG1.4.1

<h2> Environment Details:</h2>
URL: https://opensource.microsoft.com/

<h2> OS and Browser Details:</h2>
Microsoft Windows 10 Enterprise Version 21H1 (OS build 19043.1165)
Microsoft Edge Version 95.0.1000.0 (Official build) dev (64-bit)

<h2>Repro Steps:</h2>

1. Hit the URL:https://opensource.microsoft.com/
2. Check whether the  "Open Source" link present in the footer section is provided with a underline or not.

<h2> Actual Result:</h2>
The "Open Source" link present in the footer section is not provided with a underline.

<h2>Expected Result:</h2>
The "Open Source" link present in the footer section should be provided with a underline.

<h2>User Impact:</h2>
Users with low vision may not be able to identify link for the "Open Source" link present in the footer section , if it is not provided with a underline.

<h2> Attachments for reference:</h2>

![#120_Use of Color_The Open Source link present in the footer section is not provided with a underline](https://user-images.githubusercontent.com/90394513/132855140-09d1347e-38bf-493b-b038-46d2bc3cafdd.png)

**Comment by setaskin** [comment] 2021-10-06 00:03
@Rachita98 , the bug is showing up under Live Share service in S360 by mistake.  It does belong to another team. Please update the service name

**Comment by mpcen** [comment] 2022-02-08 20:20
Fixed in https://github.com/microsoft/opensource.microsoft.com/pull/171

**Comment by Aaron-Junker** [comment] 2022-03-13 18:53
I can't confirm that this is fixed, so I'll leave it open

**Closed** 2022-03-13 19:07 UTC
Labels: bug

**Comment by AnKushSingh05** [comment] 2023-02-02 09:01
#Closed
Regressed the issue in the below environment.
URL: https://opensource.microsoft.com/
The issue is fixed. Hence closing the bug.
