### ISSUE TITLE
A11y_OSPO Production_Top Navigation_High Contrast: In high contrast white, the "Microsoft" , "open source" in top navigation and the "search" icon is not visible

### ISSUE THREAD

**Issue by Rachita98** [microsoft/opensource.microsoft.com#118] opened 2021-09-10 07:33 UTC
<h2> GitHub Tags:</h2>
#A11yTCS;#A11yMAS;#Win10;#DesktopWeb;#ChromiumEgde;#A11ySev2;#P2_WCP;#WCP;#P2_OSPOProduction_Web_Sep2021;#P2_OSPOProduction;#OSPO Production;#WCAG4.3.1;#HighContrast

<h2> Environment Details:</h2>
URL: https://opensource.microsoft.com/

<h2> OS and Browser Details:</h2>
Microsoft Windows 10 Enterprise Version 21H1 (OS build 19043.1165)
Microsoft Edge Version 95.0.1000.0 (Official build) dev (64-bit)

<h2>Pre-Requisite:</h2>
To apply high contrast follow the below steps:
1. Open settings, tab till Ease of Access and press enter
2. Tab till high contrast under Vision and press enter
3. Turn on high contrast and select high contrast black/white from choose a theme combo box .
4. Select apply 

<h2> Repro Steps:</h2>
1. Turn on High Contrast white.
2. Hit the URL:https://opensource.microsoft.com/
3. Check whether the "Microsoft", "open source" in top navigation and the "search" icon is visible or not in high contrast white.

<h2>Actual Result:</h2>
In high contrast white, the  "Microsoft" , "open source" in top navigation and the "search" icon is not visible

<h2> Expected Result:</h2>
 In high contrast white, the "Microsoft", "open source" in top navigation and the "search" icon should be visible.

<h2>User Impact:</h2>
Users with low vision may not understand the content clearly if, the "Microsoft" ,"open source" in top navigation and the "search" icon is not properly visible in high contrast white.

<h2>Attachments for reference:</h2>
 **Normal View:**

![#118_Normal](https://user-images.githubusercontent.com/90394513/132819273-6f5c7a93-2f8d-4535-a45c-5f3e5b97ebec.png)

**High Contrast White Mode**
![#118_High Contrast_In high contrast white, the open source in top navigation and the search icon is not visible](https://user-images.githubusercontent.com/90394513/132818759-234920cb-d149-4978-99f9-424ed67d2f9d.png)

**Comment by setaskin** [comment] 2021-10-06 00:04
@Rachita98 , the bug is showing up under Live Share service in S360 by mistake. It does belong to another team. Please update the service name

**Comment by Rachita98** [comment] 2021-10-07 05:18
@setaskin  Thanks for letting us know. I have changed the service name.

**Comment by mpcen** [comment] 2022-02-08 20:20
Fixed in https://github.com/microsoft/opensource.microsoft.com/pull/171

**Comment by Aaron-Junker** [comment] 2022-03-13 18:58
I can't confirm this is fixed, so I'll leave it open

**Closed** 2022-03-13 19:07 UTC
Labels: bug

**Comment by AnKushSingh05** [comment] 2023-02-02 08:59
#Closed
Regressed the issue in the below environment.
URL: https://opensource.microsoft.com/
The issue is fixed. Hence closing the bug.
