### ISSUE TITLE
A11y_OSPO Production_Open Collaborative_Reflow: The "Collaborative" text is getting truncated when zoomed to 400%.

### ISSUE THREAD

**Issue by Rachita98** [microsoft/opensource.microsoft.com#124] opened 2021-09-20 07:28 UTC
<h2>GitHub Tags:</h2>
#A11yTCS;#A11yMAS;#Win10;#DesktopWeb;#ChromiumEgde;#A11ySev1;#P2_WCP;#WCP;#P2_OSPOProduction_Web_Sep2021;#P2_OSPOProduction ;#WCAG1.4.10;#Reflow;#OSPO Production;

<h2> Environment Details:</h2>
URL: https://opensource.microsoft.com/

<h2> OS and Browser Details:</h2>
Microsoft Windows 10 Enterprise Version 21H1 (OS build 19043.1165)
Microsoft Edge Version 95.0.1000.0 (Official build) dev (64-bit)

<h2> Repro Steps:</h2>

1. Change the display resolution to 1280*1024 and zoom the page to 400%.
2. Hit the URL:https://opensource.microsoft.com/
3. Check whether the "Collaborative" text is getting truncated when zoomed to 400% or not.

<h2> Actual Result:</h2>
The "Collaborative" text is getting truncated when zoomed to 400%.

<h2> Expected Result:</h2>
The "Collaborative" text should not get truncated when zoomed to 400%.

<h2> User Impact:</h2>
Users with low vision may find it difficult to understand if data is truncated in 400% zoom.

<h2> Attachments for reference:</h2>

![#124_Reflow_The Collaborative text is getting truncated when zoomed to 400%](https://user-images.githubusercontent.com/90394513/133968816-465e16dd-188c-4c7e-b670-c6822660f605.png)

**Comment by setaskin** [comment] 2021-10-05 23:53
@Rachita98  Hi , the bug is showing up under Live Share by mistaken in S360. Please change the service name

**Comment by mpcen** [comment] 2021-12-13 20:35
fixed in #149

**Closed** 2022-03-13 19:06 UTC
Labels: bug

**Comment by AnKushSingh05** [comment] 2023-02-02 09:03
#Closed
Regressed the issue in the below environment.
URL: https://opensource.microsoft.com/
The issue is fixed. Hence closing the bug.
